from services.workload_generator import WorkloadConfig


def generate_migration_sql(config: WorkloadConfig) -> str:
    """
    Generates the migration SQL a user needs to convert their
    vanilla Postgres table to a TimescaleDB hypertable.
    """

    columns = [f"    {config.timestamp_column} TIMESTAMPTZ NOT NULL"]
    for col in config.value_columns:
        columns.append(f"    {col} DOUBLE PRECISION")

    columns_sql = ",\n".join(columns)

    sql = f"""-- ============================================
-- Migration: Postgres → TimescaleDB
-- Generated by Postgres to Tiger
-- ============================================

-- Step 1: Make sure TimescaleDB extension is installed
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- Step 2: Create your table (skip if it already exists)
CREATE TABLE IF NOT EXISTS {config.table_name} (
{columns_sql}
);

-- Step 3: Convert to hypertable
-- This is the key step — it enables time-based partitioning
SELECT create_hypertable(
    '{config.table_name}',
    '{config.timestamp_column}',
    if_not_exists => TRUE
);

-- Step 4: (Optional but recommended) Enable compression
-- Compresses chunks older than 7 days — typically 90-95% size reduction
ALTER TABLE {config.table_name}
SET (
    timescaledb.compress,
    timescaledb.compress_orderby = '{config.timestamp_column}'
);

SELECT add_compression_policy(
    '{config.table_name}',
    INTERVAL '7 days'
);

-- Step 5: (Optional) Add a continuous aggregate for fast dashboards
-- Replaces slow GROUP BY queries with pre-computed results
CREATE MATERIALIZED VIEW {config.table_name}_hourly
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 hour', {config.timestamp_column}) AS bucket,
    {', '.join([f"AVG({col}) AS avg_{col}" for col in config.value_columns])}
FROM {config.table_name}
GROUP BY bucket
WITH NO DATA;

SELECT add_continuous_aggregate_policy(
    '{config.table_name}_hourly',
    start_offset => INTERVAL '30 days',
    end_offset   => INTERVAL '1 hour',
    schedule_interval => INTERVAL '1 hour'
);

-- ============================================
-- Done! Your table is now a TimescaleDB hypertable.
-- ============================================
"""
    return sql.strip()
